# Case-sensitive paths to include during linting.
included:
  - MangaViewer

# case-sensitive paths to ignore during linting.
excluded:
  - MangaViewer/Core/Cache # We have Objc code here, remove in future.

# Enabled/disabled rules
analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - all

disabled_rules:
  - contrasted_opening_brace
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - indentation_width
  - no_magic_numbers
  - one_declaration_per_file
  - required_deinit
  - type_contents_order
  - vertical_whitespace_between_cases
  - attributes
#  - anonymous_argument_in_multiline_closure
#  - conditional_returns_on_newline
#  - convenience_type
#  - discouraged_optional_collection
#  - explicit_enum_raw_value
#  - force_unwrapping
#  - function_default_parameter_at_end
#  - missing_docs
#  - multiline_arguments
#  - multiline_arguments_brackets
#  - multiline_function_chains
#  - multiline_parameters_brackets
#  - no_extension_access_modifier
#  - no_grouping_extension
#  - prefer_nimble
#  - prefixed_toplevel_constant
#  - sorted_enum_cases
#  - strict_fileprivate
#  - switch_case_on_newline
#  - todo
#  - trailing_closure

closure_body_length:
    warning: 50
    error: 100

trailing_comma:
  mandatory_comma: true

identifier_name:
  excluded:
    - id

redundant_type_annotation:
  consider_default_literal_types_redundant: true
